# Generated by Django 4.2.4 on 2023-09-01 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last name')),
                ('contacts', models.TextField(blank=True, null=True, verbose_name='contacts')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('logo', models.CharField(max_length=255, verbose_name='logo')),
                ('channel_background', models.CharField(blank=True, max_length=255, null=True, verbose_name='channel background')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
