# Generated by Django 4.2.4 on 2023-09-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='length',
            new_name='duration',
        ),
    ]
